# Optional C++20 named module support for std_fix (opt-in, off by default).
#
# Adds a target, `std_fix_module` (alias `Psi::StdFixModule`), exporting std_fix's public headers
# as `import std_fix;` instead of textual #include. Purely additive.
#
# Shape: one interface unit whose global module fragment carries the real STL headers std_fix's
# patches build on top of (modules never export macros, so anything macro-only would also belong
# here, but std_fix has nothing that qualifies); the purview (`export extern "C++"`) carries every
# real header via file(GLOB_RECURSE) matched to std_fix's actual naming convention: most headers
# under include/std_fix/ mirror standard-library header names with NO extension (bit, concepts,
# memory, algorithm, fix_version), a few use `.hpp` (const_iterator.hpp, ranges/*.hpp) - so the
# glob below matches every file under include/, not just *.hpp.
#
# std_fix's patches are gated on standard feature-test macros (`__cpp_lib_bit_cast`,
# `__cpp_lib_ranges`, ...): on a sufficiently modern STL every gate is already closed and a header
# degrades to a transparent forward to the real declarations. The module purview still has to
# survive being compiled that way - this target exists to prove exactly that, not to prove the
# gated fix bodies themselves execute (that needs an outdated STL, which this toolchain isn't).
#
# std_fix reopens `namespace std` directly (unlike header-only libraries that only add their own
# namespace). Reopening it inside `export extern "C++" { ... }` was verified empirically before
# writing this file: a standalone probe wrapped a `namespace std` template declaration in
# `export extern "C++"`, and a consumer both `import`-ed the module and textually `#include`d the
# same real header in the same translation unit; it built and ran clean. Per [module.unit], names
# declared within a linkage-specification (extern "C" or extern "C++") are attached to the global
# module even when the linkage-specification appears inside a module purview - so this does not
# give std_fix's `std` additions module ownership, which is exactly what avoids an ODR/attachment
# conflict against the same headers textually #include-d elsewhere.
#
# Toolchain: clang-cl and the GNU-driver clang only; MSVC/GCC get a warning, not a hard error.

option( STD_FIX_MODULE "Build std_fix as a C++20 named module (opt-in; requires clang-cl or clang)" OFF )

if ( STD_FIX_MODULE )
    if ( NOT ( CMAKE_CXX_COMPILER_ID MATCHES Clang ) )
        message( WARNING "STD_FIX_MODULE requires clang-cl or clang; ignored on ${CMAKE_CXX_COMPILER_ID}." )
    else()
        if ( CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC" )
            cmake_path( GET CMAKE_CXX_COMPILER PARENT_PATH _std_fix_llvm_bin )
            find_program( STD_FIX_CLANG_SCAN_DEPS clang-scan-deps HINTS "${_std_fix_llvm_bin}" REQUIRED )
            string( CONCAT CMAKE_CXX_SCANDEP_SOURCE
                "\"${STD_FIX_CLANG_SCAN_DEPS}\" -format=p1689 -- <CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS>"
                " /TP <SOURCE> /c /Fo<OBJECT> /clang:-MT /clang:<DYNDEP_FILE> /clang:-MD /clang:-MF /clang:<DEP_FILE>"
                " > <DYNDEP_FILE>.tmp && \"${CMAKE_COMMAND}\" -E rename <DYNDEP_FILE>.tmp <DYNDEP_FILE>" )
            set( CMAKE_CXX_MODULE_MAP_FORMAT clang )
            set( CMAKE_CXX_MODULE_MAP_FLAG "@<MODULE_MAP_FILE>" )
            set( CMAKE_CXX_COMPILE_BMI "<CMAKE_CXX_COMPILER> <DEFINES> <INCLUDES> <FLAGS> /clang:-o<OBJECT> /clang:--precompile /TP <SOURCE>" )
        endif()

        file( GLOB_RECURSE std_fix_module_headers RELATIVE "${CMAKE_CURRENT_LIST_DIR}/include" "${CMAKE_CURRENT_LIST_DIR}/include/*" )
        list( FILTER std_fix_module_headers EXCLUDE REGEX "\\.md$" ) # drop any stray non-header files the glob picks up

        set( _std_fix_module_purview "${CMAKE_CURRENT_BINARY_DIR}/std_fix_module_purview.hpp" )
        set( _std_fix_module_content "// Generated by module.cmake - every std_fix public header, cumulative.\n" )
        foreach( h ${std_fix_module_headers} )
            string( APPEND _std_fix_module_content "#include <${h}>\n" )
        endforeach()
        file( WRITE "${_std_fix_module_purview}" "${_std_fix_module_content}" )

        set( _std_fix_module_unit "${CMAKE_CURRENT_BINARY_DIR}/std_fix_module.cppm" )
        file( WRITE "${_std_fix_module_unit}" "\
module;
// std_fix's own headers are patches on top of these - pre-including them here (global module
// fragment) means the purview's re-inclusion (via std_fix's own #include guards / #pragma once)
// is a no-op, so only std_fix's incremental (feature-test-gated) content is ever in the purview.
#include <version>
#include <bit>
#include <algorithm>
#include <ranges>
#include <concepts>
#include <type_traits>
#include <utility>
#include <iterator>
#include <memory>
#include <cstdint>

export module std_fix;
export extern \"C++\"
{
#include \"${_std_fix_module_purview}\"
}
" )

        add_library( std_fix_module STATIC )
        add_library( Psi::StdFixModule ALIAS std_fix_module )
        target_compile_features( std_fix_module PUBLIC cxx_std_23 )
        target_sources( std_fix_module PUBLIC FILE_SET CXX_MODULES BASE_DIRS "${CMAKE_CURRENT_BINARY_DIR}" FILES "${_std_fix_module_unit}" )
        target_include_directories( std_fix_module PUBLIC "${CMAKE_CURRENT_LIST_DIR}/include" )
        target_compile_options( std_fix_module PRIVATE
            $<$<CXX_COMPILER_FRONTEND_VARIANT:MSVC>:/clang:-std=gnu++2c /clang:-Wno-include-angled-in-module-purview /clang:-Wno-reserved-module-identifier>
            $<$<NOT:$<CXX_COMPILER_FRONTEND_VARIANT:MSVC>>:-Wno-include-angled-in-module-purview -Wno-reserved-module-identifier>
        )
    endif()
endif()
